### ISSUE TITLE
Error fetching /formList with Briefcase

### ISSUE THREAD

**Issue by FranckVachon** [kobotoolbox/dist-kobo-devel#29]
Unsure if Briefcase is supposed to work with the Kobo vm or not - however when trying to use it here's what happens. I actually type in the browser the address that Briefcase report a 500 errror at, in other words:

http://127.0.0.1:8001/formList

You are then asked for the Kobo VM credentials. In Briefcase I entered kobo & kobo, and I entered the very credential in the browser whent it pop up. Then error message from django:

Error message: =======================================================
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8001/formList

Django Version: 1.6.11
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.gis',
 'registration',
 'south',
 'reversion',
 'django_nose',
 'django_digest',
 'corsheaders',
 'oauth2_provider',
 'rest_framework',
 'rest_framework.authtoken',
 'taggit',
 'readonly',
 'onadata.apps.logger',
 'onadata.apps.viewer',
 'onadata.apps.main',
 'onadata.apps.restservice',
 'onadata.apps.api',
 'guardian',
 'djcelery',
 'onadata.apps.stats',
 'onadata.apps.sms_support',
 'onadata.libs')
Installed Middleware:
('onadata.koboform.redirect_middleware.ConditionalRedirects',
 'reversion.middleware.RevisionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'onadata.libs.utils.middleware.LocaleMiddlewareWithTweaks',
 'django.middleware.csrf.CsrfViewMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.transaction.TransactionMiddleware',
 'onadata.libs.utils.middleware.HTTPResponseNotAllowedMiddleware',
 'readonly.middleware.DatabaseReadOnlyMiddleware')

Traceback:
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  57.         return view_func(*args, **kwargs)
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/rest_framework/viewsets.py" in view
  79.             return self.dispatch(request, *args, **kwargs)
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  403.             response = self.handle_exception(exc)
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  391.             self.initial(request, *args, **kwargs)
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/rest_framework/views.py" in initial
  320.         self.perform_authentication(request)
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/rest_framework/views.py" in perform_authentication
  270.         request.user
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/rest_framework/request.py" in user
  226.             self._authenticate()
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/rest_framework/request.py" in _authenticate
  401.                 user_auth_tuple = authenticator.authenticate(self)
File "/home/vagrant/src/kobocat/onadata/libs/authentication.py" in authenticate
  18.         if self.authenticator.authenticate(request):
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/django_digest/__init__.py" in authenticate
  97.         partial_digest = self._account_storage.get_partial_digest(digest_response.username)
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/django_digest/backend/storage.py" in get_partial_digest
  23.         cursor = self.db.connection.cursor()
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/django/db/backends/__init__.py" in cursor
  157.         self.validate_thread_sharing()
File "/home/vagrant/.virtualenvs/kc/local/lib/python2.7/site-packages/django/db/backends/__init__.py" in validate_thread_sharing
  499.                 % (self.alias, self._thread_ident, thread.get_ident()))

Exception Type: DatabaseError at /formList
Exception Value: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id -1391477952 and this is thread id -1410340032.
END ERROR ===============================================================

**Comment by tinok** [comment]
This was fixed with [this commit](https://github.com/kobotoolbox/kobocat/commit/e977638e2a72935d54e0b9b5cb7118857d02c03f). Will be available through dist-kobo-devel once it's been merged into master.

**Comment by ratnahalder** [comment]
@tinok  Databasewrapper error still present in kobotoolbox after adding your modified code :( have any another solution please?
