### ISSUE TITLE
Use the new kc_environ settings file for kobocat

### ISSUE THREAD

**Issue by hossein** [kobotoolbox/dist-kobo-devel#38]
Since kobocat_settings was [included in kobocat repo](https://github.com/kobotoolbox/kobocat/commit/28fb9e97e25c0998b20c3014b6ef1367555f6550) as [kc_environ](https://github.com/kobotoolbox/kobocat/commit/704ce83dcc67cd35ae2f6cd3cb64dd7e85acfccd) and [MongoDB settings were moved from setting.common to this new kc_environ](https://github.com/kobotoolbox/kobocat/commit/91e6ea6f2fa6ad102e3db6cb2697df9e8c3724d9), on a new vagrant installation you'll get errors at  kc_50 script nagging about settings.MONGO_DB not being defined.

The plan is to use the new kc_environ as the settings module and remove `env/kobocat_settings.py` from dist-kobo-devel?

**Comment by davidmaxwell** [comment]
@hossein did you get a work-around for this?

**Comment by dorey** [comment]
The `kc_environ` settings file is intended for our production environment which is using docker. I'll fix this by adding MONGO_DB to this repository's kobocat_settings.

**Comment by dorey** [comment]
I have made a pull request from branch `issue-38` which should fix this, however I won't be able to confirm that it works until tomorrow. @davidmaxwell , if you recently ran into this issue, this branch should fix the problem.

PS. If you want to try out a dockerized solution please send us a message the kobo support email.

**Comment by rumman0786** [comment]
@dorey the new settings file the you modified works. thanks a lot. however this is still not included with the master branches' settings file and many will run into the same problem.
